apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgresSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: auction-secret
type: Opaque
stringData:
  connString: 'Server=postgres-clusterip:5432;User Id=postgres;Password=postgresSecretPw;Database=auctions'
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: mongoUn
  password: mongoSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: rabbitUn
  password: rabbitSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: search-secret
type: Opaque
stringData:
  connString: mongodb://mongoUn:mongoSecretPw@mongo-clusterip
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
stringData:
  authSecret: thisisevenmoresecretthanprevioussecrets
---
apiVersion: v1
kind: Secret
metadata:
  name: bid-secret
type: Opaque
stringData:
  connString: 'mongodb://mongoUn:mongoSecretPw@mongo-clusterip'
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
type: Opaque
stringData:
  connString: 'Server=postgres-clusterip:5432;User Id=postgres;Password=postgresSecretPw;Database=identity'